### ISSUE TITLE
set up this repo to deploy thecircuit.cc

### ISSUE THREAD

**Issue by fgregg** [datamade/circuit#1]
Right now thecircuit.cc is deployed from https://github.com/designhawg/circuit

I think we can make all the change we need to do this from netlify

**Comment by fgregg** [comment]
@smcalilly is this done?

**Comment by smcalilly** [comment]
@fgregg no, i haven't done this yet. was trying to finish issue #2 first.

**Comment by smcalilly** [comment]
@fgregg I've set up the site to deploy from netlify. You can see a deployment here: https://determined-bose-741b18.netlify.app/. 

Do you know what all we need to do for the DNS? It looks easily configurable on netlify's end: https://app.netlify.com/sites/determined-bose-741b18/overview

**Comment by fgregg** [comment]
thanks @smcalilly, i dealt with the DNS. (there was some complication, and i did it through cloudflare)
