### ISSUE TITLE
Feedback on the circuit

### ISSUE THREAD

**Issue by fgregg** [datamade/circuit#10]
@smcalilly feedback from @oobineme. Numbers correspond to the markers in the images.

- [x] 1. Looks awkward in mobile. Can we make the contact info 2em in font size?
- [x] 2. Can we make this question copy 3em with 30px padding?
<img width="525" alt="screen_shot_2021-08-20_at_4 11 16_pm" src="https://user-images.githubusercontent.com/536941/130623527-cbaaabfd-03ad-4836-b47d-86288ef370be.png">

- [x] 4. Can we make these social icons 75% of its current size?
- [x] 5. Can we give a a bit more space between subhed and the copy above it?
- [x] 6. Can we make the subhed copy 1.8em?
- [x] 7. Can we make these buttons 75% of its existing height?
- [x] 10. Can we bring this down? and bring a bit and enlarge it twice its size. Let's also try lowering the opacity by close to half? Also very OK if this was cut. I would just choose between these options.
Mobile view feedback:
- [x] 11. Can we provide triple the current line spacing between button and next subhed? (unless this will be responsive automatically from desktop view changes of some of the font size edits :woman-shrugging::skin-tone-5:) 
<img width="928" alt="screen_shot_2021-08-20_at_4 17 36_pm" src="https://user-images.githubusercontent.com/536941/130623929-8e5059a1-f70a-4f4e-8b65-9b5e778f2380.png">

**Comment by smcalilly** [comment]
@fgregg @oobineme I made those changes. You can preview here: https://deploy-preview-7--thecircuit.netlify.app/connect/

For number 10, I simply cut it. Let me know if you'd rather have the image and I can add it back with the styling based on that note.
