### ISSUE TITLE
Add a connect page to the circuit.

### ISSUE THREAD

**Issue by fgregg** [datamade/circuit#2]
Here's a wireframe that (Frame 5) of what they would like it look like:  https://www.figma.com/file/UdnFT4Dgd213eIhzQ0jyUy/Circuit-Engagement?node-id=11%3A8

Copy here: https://docs.google.com/document/d/1vG_AjVsWeY3qhAyi_gTM80dwN6_5wb6AoHLPApssUSk/edit#

The engagement form should be the one that we have on detail pages for for the charges site: https://61114cf6d04c4906358f63ae--court-transparency-charges.netlify.app/en/theft

**Comment by fgregg** [comment]
Build list:

* add page
* add copy
* source assets
  * image with the card
  * twitter logo
...

**Comment by smcalilly** [comment]
@fgregg your suggested build list looks good to me. More detailed:

- create new page
- add copy, which will help establish the layout
- add contact form
- source assets and add them to the page
  - image at the top
  - social logos
- add footer

**Comment by smcalilly** [comment]
@fgregg just fyi, here is where i'm at on this page
![circuit-connect](https://user-images.githubusercontent.com/38969506/129109865-f0150755-5562-458b-ad2b-c84d2743db32.gif)


work to do:
- integrate the contact form backend. this is a big unknown. the charges app somehow uses netlify for the form, so we'll have to figure that out.
- add the main image
- add social images
- add a few missing links
- tighten up some spots to match the design

**Comment by fgregg** [comment]
thanks for the update. do you need help figuring out the form?

**Comment by smcalilly** [comment]
@fgregg The [form looks straightforward](https://docs.netlify.com/forms/setup/) (and a nice feature from Netlify), though I will let you know if I get stuck. I just made all those changes listed in my last comment, and going to test out the deployment. This will let me test the form, too. I'm planning have a PR later this afternoon.
